name: EAS Build

on:
  workflow_dispatch:  # allows you to trigger manually in GitHub Actions tab

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Run APK build (preview profile)
      - name: Build APK
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Run AAB build (production profile, optional)
      - name: Build AAB
        run: eas build -p android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
