name: EAS Android APK

on:
  workflow_dispatch: {}

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Use npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Verify Expo token
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build APK (preview)
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}



name: EAS Build

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend   # <-- your Expo project folder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      # (Optional) Show where we are
      - run: pwd && ls -la

      # Ensure this project is linked to an EAS project
      - name: Verify EAS linkage
        run: |
          node -e "const fs=require('fs');const j=require('./app.json');const id=j?.expo?.extra?.eas?.projectId; if(!id){process.exit(2)}"
        continue-on-error: true

      # If not linked, fail with a clear message
      - name: Stop if not linked to EAS
        if: ${{ steps.Verify_EAS_linkage.outcome == 'failure' }}
        run: |
          echo "::error::This repo isn't linked to an EAS project. See instructions in job log."
          exit 1

      - name: Build APK (preview)
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_DEBUG: "1"
