name: Generate Android Keystore
on:
  workflow_dispatch:

jobs:
  gen-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random passwords
        id: pw
        run: |
          KEYSTORE_PASSWORD=$(openssl rand -base64 24 | tr -d '=+/')
          KEY_PASSWORD=$(openssl rand -base64 24 | tr -d '=+/')
          echo "keystore_password=$KEYSTORE_PASSWORD" >> $GITHUB_OUTPUT
          echo "key_password=$KEY_PASSWORD" >> $GITHUB_OUTPUT
          echo "alias=upload" >> $GITHUB_OUTPUT

      - name: Create upload keystore
        run: |
          keytool -genkeypair -v \
            -keystore upload-keystore.jks \
            -storepass "${{ steps.pw.outputs.keystore_password }}" \
            -keypass   "${{ steps.pw.outputs.key_password }}" \
            -alias     "${{ steps.pw.outputs.alias }}" \
            -dname "CN=DailyBite, OU=Apps, O=DailyBite, L=Zurich, S=ZH, C=CH" \
            -keyalg RSA -keysize 2048 -validity 10000

      - name: Base64 encode keystore
        id: b64
        run: |
          echo "b64=$(base64 -w 0 upload-keystore.jks)" >> $GITHUB_OUTPUT

      - name: Show outputs (copy these into GitHub Secrets)
        run: |
          echo "ANDROID_KEYSTORE_BASE64=${{ steps.b64.outputs.b64 }}"
          echo "ANDROID_KEYSTORE_PASSWORD=${{ steps.pw.outputs.keystore_password }}"
          echo "ANDROID_KEY_ALIAS=${{ steps.pw.outputs.alias }}"
          echo "ANDROID_KEY_PASSWORD=${{ steps.pw.outputs.key_password }}"

      - name: Upload keystore as artifact (optional download)
        uses: actions/upload-artifact@v4
        with:
          name: upload-keystore.jks
          path: upload-keystore.jks
